title: Prajwal's Portfolio
logo: https://media.licdn.com/dms/image/D5603AQEp5fJUTxNq2w/profile-displayphoto-shrink_800_800/0/1679943299244?e=1709769600&v=beta&t=j92XlQnCUT8RWfv3HjRNbICNjyvgKY0LErP8Q7LhuyA
description: Resume/Portfolio of Prajwal Nautiyal
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal