title: Hi, I'm Prajwal
logo: /assets/img/Prajwal.jpg
description: Email > prajwalnautiyal2003@gmail.com Phone > +1 (365) 999-3537
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal